server:
  port: 8080
spring:
  datasource:
      name: glmapper
      url: jdbc:mysql://127.0.0.1:3306/glmapper
      username: root
      password: glmapper
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html; charset=utf-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      suffix: .ftl
      template-loader-path: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.glmapper.book.model
logging:
  config: classpath:logback-boot.xml

